import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div classNameName={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="container">
        <div className="row">
            <div className="col-lg-4">
                <Image src="/logo.png" width="1000"height="1000" />
               
            </div> 
            <div className="col-lg-4">
                SM te ayuda a comunicarte y compartir tus obras con las personas que forman parte del mundo del arte.
            </div>
            <div className="col-lg-3">
                <div className="shadow-lg p-4 mb-5 bg-body rounded">   
                  <form method="POST">
                    <label htmlFor="name">Name</label>
                    <input id="name" type="text" autoComplete="name" required />
                    <button type="submit">Register</button>
                  </form>
                </div>
            </div>
        </div>
    </div>

      
    </div>
  )
}
